### ISSUE TITLE
Weird console error; all custom crafting recipes disabled.

### ISSUE THREAD

**Issue by Samaine** [WolfyScript/CustomCrafting#102]
### What happened?

All custom crafting recipes are disabled;
![2022-04-01_18 00 27](https://user-images.githubusercontent.com/13899540/161231327-faa7380d-1b2b-41c5-8e83-769ffb0f5bf8.png)
Looks like the following. 

### How can the bug be reproduced?

After updating the plugin, the error started.

### Expected Behaviour?

Not this.

### Plugin version

customcrafting-spigot-3.16.3.2, wolfyutilities-3.16.3.2

### Server software

Paper-409 (1.17.1)

### Relevant log output

```shell
https://pastebin.com/uJ2wSmqs
Console log of the bug.
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
That issue will be fixed soon.
The issue only affects the default recipes. All other recipes should still be loaded.
If that is not the case you can delete the `/data/customcrafting` folder and disable the default recipes in the config under `recipe_book.reset` and `crafting_table.reset`
