### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by SignorPollito** [WolfyScript/CustomCrafting#115]
### What happened?

When you are making a recipe and you "SHIFT + Left click" the result slot to get all the items, the items gets duplicated.
This bug seems to be really hard to replicate and always happens when there are more items inside the crafting matrix.

I actually don't understand how and when it happens, but I figured out that spamming "SHIFT + Left click" makes this bug more often.

### How can the bug be reproduced?

1. Make a custom recipe
2. Place all the items inside the crafting table to make that recipe
3. Start spam-clicking "SHIFT + Left click" on the result slot
4. And then it will eventually duplicate the crafting matrix's items

This is an example on how to do it, I sugged you to try with pickaxes too:
https://imgur.com/a/1mfqXgf

### Expected Behaviour?

The items inside the crafting matrix should not be duped.

### Plugin version

CustomCrafting 3.16.3.3, WolfyUtilities 3.16.3.2

### Server software

Purpur 1.16.5

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
This is in-fact a very well known issue. Unfortunately, I haven't found a fix for it yet. 
I think I might have a solution. I try to put that change into place for the next update.
