### ISSUE TITLE
color tags not working

### ISSUE THREAD

**Issue by 1Pootis1** [WolfyScript/CustomCrafting#119]
### What happened?

When editing an item, namely, when you set a name or lore for it, the color tags do not work, see Figure 1

![image](https://user-images.githubusercontent.com/73141732/167502047-421997ff-d101-4b30-9801-dce6be493e81.png)

### How can the bug be reproduced?

change name for item and with color tag

### Expected Behaviour?

Colored text

### Plugin version

customcrafting-spigot-3.16.3.3, wolfyutilities-3.16.3.2

### Server software

Paper 1.17.1, build 409

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
These legacy color codes are slowly phased out of WolfyUtilities and CustomCrafting.
Instead it uses the Adventure API and its MiniMessage format.
Format: https://docs.adventure.kyori.net/minimessage/format.html
Online Web Viewer: https://webui.adventure.kyori.net/
