### ISSUE TITLE
PlaceholderAPI Condition

### ISSUE THREAD

**Issue by BeepoWuff** [WolfyScript/CustomCrafting#122]
### The Problem

There are many arbitrary conditions that users may want on their recipes that aren't supported by existing conditions and most likely won't be with future conditions if they are super specific.

### Solution

In the same vein as #79 it may be worth adding a more generalised comparison condition that instead of comparing scoreboard values can compare the resolved value of a PlaceholderAPI placeholder.
The sheer number of placeholders available via plugins means this could be useful in quite a few different scenarios.

### Alternatives

You can achieve similar functionality if you're using LuckPerms by using the [ExtraContexts](https://luckperms.net/wiki/Context#extracontexts) addon with the [PlaceholderAPI Context](https://github.com/LuckPerms/ExtraContexts#placeholderapi) to dynamically assign a permission based on the context which you then use in a recipe permission condition... but that's fairly complicated

### Additional Context

An example use case that was brought up in the Discord server was restricting a recipe to only be available during certain real world dates for events, holidays, etc.
In this case the `%server_time_<SimpleDateFormat>%` placeholder set to just output date without time would be prime for comparisons.

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
I just realised that WolfyUtilities provides the `ValueProviderPlaceholderAPI` that can be used inside checks with the player eval context.
Gonna create a general custom check condition instead.
