### ISSUE TITLE
Retain CustomModelData for items in GUI for icons

### ISSUE THREAD

**Issue by LcorpOfficial** [WolfyScript/CustomCrafting#133]
### The Problem

When setting a category in the recipe book, for example, the item will return to it's base form and remove all NBT associated with it. 

### Solution

The item placed in the icon slot for a category should retain the CustomModelData it has so that customization is more available for custom recipe book GUIs

### Alternatives

N/A

### Additional Context

N/A

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Oops, forgot to close this. I implemented it in CC 3.16.7.
