### ISSUE TITLE
Error on startup, not loading plugins

### ISSUE THREAD

**Issue by SignorPollito** [WolfyScript/CustomCrafting#139]
### What happened?

When using the latest version of CustomCrafting and WolfyUtilities my plugins don't load, throwing the error:
-------------------------------------------------------
[Server thread/ERROR]: Could not load 'plugins/NAME.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/google/inject/AbstractModule
-------------------------------------------------------

If I remove CustomCrafting and WolfyUtilities or I use an older version of those plugins it works as expected.
As in my plugins I use Juice, I think that there is something in WolfyUtilities or CC that just removes, for some reason, that library.

And, when CC is fully loaded, it throws that exception:
https://pastebin.com/Zg4wujn8

### How can the bug be reproduced?

- Make a custom plugin and use Juice inside of it
- Start the server with the latest version of WU and CC
- The error should now appear

### Expected Behaviour?

The error should not be thrown and the plugins using Juice should load up without any problem.

### Plugin version

CustomCrafting 3.16.4.0, WolfyUtilities 4.16.2.0

### Server software

Purpur 1.16.5 (Java 17)

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
You would have to shade and **relocate** juice in your plugin, or use the libraries option in your plugin.yml without shading it.
If you do not relocate dependencies, it'll conflict with other plugins that also do not relocate it or are using the libraries feature!

> And, when CC is fully loaded, it throws that exception:
> https://pastebin.com/Zg4wujn8
That error is fixed in WolfyUtilities v4.16.3.0-beta
