### ISSUE TITLE
A "back" button

### ISSUE THREAD

**Issue by Zzeyy** [WolfyScript/CustomCrafting#171]
### The Problem

It's really good that there is a button to turn a page,
but why is there no button to go to the previous page?

### Solution

Add a similar button to the already existing button, that will turn to the previous page.

### Alternatives

None.

### Additional Context

Nothing. Also why are the **Alternatives** and **Additional Context** boxes marked as required?

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Looks like that is already fixed since CC v4.16.0.1.
https://github.com/WolfyScript/CustomCrafting/releases/tag/v4.16.0.1

I'll release the next free build by the end of the week.
