### ISSUE TITLE
Conflict with brewery plugin

### ISSUE THREAD

**Issue by zek2468** [WolfyScript/CustomCrafting#180]
### The Problem

After cauldron's GUI was added, this broke our brewery plugin.
https://dev.bukkit.org/projects/brewery

The brewery plugin requires a cauldron to be right-clicked with items under a non-campfire flame.

After the GUI was added this overrides the brewery plugin's ability to check for rightclicks.

### Solution

Detect when a cauldron is under a camp fire and use the GUI or use the old method of dropping items in.

### Alternatives

Add the ability to disable cauldron crafting and other crafting types when a server dos not need it,

Example

UseCauldronCrafting = False #setting this to false disables just the cauldron part of CustomCrafting
UseCraftingTable = True
UseFurnace = True

### Additional Context

![Screenshot 2022-10-24 174639](https://user-images.githubusercontent.com/25335568/197636089-53fe3e0a-0d8a-4a19-9668-2bddb5aa8d2d.png)

Here is an example of how it worked befor

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
It is not really possible to provide a good compatibility between these two systems, as the CC Cauldron works without any Campfire underneath too.
However, I added a permission to the cauldron interaction. Set the perm `customcrafting.workstation.cauldron.interact` is enabled by default, so set it to `false` to the groups/players that are not allowed to open the GUI (in return, allowing Brewery).
