### ISSUE TITLE
Writable Book Pages Preserving

### ISSUE THREAD

**Issue by x8192** [WolfyScript/CustomCrafting#181]
### The Problem

Already described.

### Solution

Book pages merge adapter or something.

### Alternatives

I've considered existing adapters, but none of them apply.

### Additional Context

I need to create a recipe that adds a lore text to a writable book while preserving it's content.

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
I am still looking forward to implementing an easier and more customizable written book merge adapter.
However, that'll still take some time.

For now, I found a solution using the [NBTMergeAdapter](https://github.com/WolfyScript/CustomCrafting/wiki/Merge-Adapter-%7C-NBT).

Adding this to the result of your recipe result should merge the pages list into the NBT of the result item.
Of course, if your book is in a different ingredient slot you need to select it in `slots`.
```json
"target": {
    "mergeOptions" : [
      {
        "slots" : [ 0, 1 ],
        "adapters" : [
          {
            "key" : "customcrafting:nbt/merge",
            "query": {
              "pages": {
                "type": "list/string",
                "elements" : [
                  {
                    "value": true
                  }
                ]
              }
            }
          }
        ]
      }
    ]
  }
```
