### ISSUE TITLE
Free items in elite bench

### ISSUE THREAD

**Issue by Peskdt** [WolfyScript/CustomCrafting#194]
### What happened?

You save all needed items, and you get the crafteable item

### How can the bug be reproduced?

Evidence
[](https://youtu.be/wmq0XsXmKaI)
https://youtu.be/wmq0XsXmKaI

### Expected Behaviour?

Don't dupe items

### Plugin version

CC 4.16.3.1 WU 4.16.9.2

### Server software

Purpur 1.19.2

### Relevant log output

```shell
No logs
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Fixed in v4.16.3.2
https://github.com/WolfyScript/CustomCrafting/releases/tag/v4.16.3.2
