### ISSUE TITLE
Plugin compatibility with Brewery

### ISSUE THREAD

**Issue by xCraimax** [WolfyScript/CustomCrafting#196]
### The Problem

Custom Crafting is not compatible with the Brewing Plugin „Brewery“.
CC uses the normal „Right-Click“, to open the Menu of a cauldron.
Brewery does a similar thing:
You use the right click to put an ingredient of a potion or a drink.

The problem is, that the Brewery right-click doesn‘t work no more, while using Custom Crafting.

Brewery on SpigotMC: https://www.spigotmc.org/resources/brewery.3082/

### Solution

Creating a new config option or a general compatibility with the Brewery Plugin and CC.
A.e.  getting the option to enable/use the shift right click, to open the CC Cauldron menu.

### Alternatives

Not using CC because of the compatibility issue

### Additional Context

The plugins are quite nice to use together, as you get MANY MANY possibilities!

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
You need to set the cauldron interact permission to `false` for players/groups that shouldn't be allowed to use CustomCraftings' cauldron interaction.
https://github.com/WolfyScript/CustomCrafting/wiki/Permissions#cauldron

**Comment by xCraimax** [comment]
Thats the issue. People should be able to use it in compatibility with Brewery.

**Comment by xCraimax** [comment]
> You need to set the cauldron interact permission to `false` for players/groups that shouldn't be allowed to use CustomCraftings' cauldron interaction. https://github.com/WolfyScript/CustomCrafting/wiki/Permissions#cauldron

Soo, we tried removing the permission. That still doesn't solve the problem. When we removed the permission from the player, then we've got the following message, and it didn't use the Brewery Function.
![image](https://user-images.githubusercontent.com/49165798/215267284-a40e77dd-d7e5-4a07-bca2-3ad2948d1d39.png)

**Comment by WolfyScript** [comment]
> Thats the issue. People should be able to use it in compatibility with Brewery.

I reconsidered it, and I am going to add a sneak right-click option to the cauldron. #225

**Comment by xCraimax** [comment]
> > Thats the issue. People should be able to use it in compatibility with Brewery.
> 
> I reconsidered it, and I am going to add a sneak right-click option to the cauldron. #225

Thank you very much! Custom Crafting is a really great plugin and i‘m really excited to use CC!
