### ISSUE TITLE
Anvils makes you lose materials.

### ISSUE THREAD

**Issue by ConaII** [WolfyScript/CustomCrafting#21]
Example, you have this crafting:
![image](https://user-images.githubusercontent.com/72966048/141118252-42f12e0e-4bbd-42f1-ac06-05c509d15f96.png)
But if you use more than 1 in the first slot:
![image](https://user-images.githubusercontent.com/72966048/141118336-636cc76e-88d0-4f1b-9c6d-c787ab0f780e.png)
And you try to obtain that 1 output.
![image](https://user-images.githubusercontent.com/72966048/141118483-1400afb2-5f19-4981-8858-57683917a33c.png)
It takes all materials.
This should left 63 materials in the first slot.
Like this:
![image](https://user-images.githubusercontent.com/72966048/141118568-4abf9a4c-eb24-414d-8900-0a877f4c3dd8.png)

**Comment by WolfyScript** [comment]
This is actually expected. 
I looked through the code of the custom anvil recipes, and the reason I did it that way is that Anvil recipes are very buggy when only consuming one item. Only the second slot supports it.
I am not sure if I could fix this, without causing other issues. I will look into it.

**Comment by ConaII** [comment]
Thanks, I appreciate it.
People in my server are losing materials bc of this, I will also look into it to see if I can fix it somehow when i get back from school
