### ISSUE TITLE
Cannot pass FurnaceSmeltEvent

### ISSUE THREAD

**Issue by LcyDev** [WolfyScript/CustomCrafting#213]
### What happened?

https://paste.gg/p/ConaII_/5e51930e4db44ef88b65999be1642799

### How can the bug be reproduced?

I don't really know

### Expected Behaviour?

N/A

### Plugin version

CustomCrafting-4.16.5.1 - WolfyUtils-4.16.9.6

### Server software

Purpur 1.19.3 (#1894)

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Looks like I missed an equal sign in the code... whoops.
It is fixed now and in the upcoming final release.
