### ISSUE TITLE
[DUPE] Anvil recipes keep refilling items "spent"

### ISSUE THREAD

**Issue by LcyDev** [WolfyScript/CustomCrafting#214]
### What happened?

https://user-images.githubusercontent.com/72966048/212495276-9845d903-7105-49e8-a0c5-0f6b6707f1e5.mp4

### How can the bug be reproduced?

Create a simple anvil recipe and try using it

### Expected Behaviour?

This didn't happen in previous versions

### Plugin version

CustomCrafting-4.16.5.1 - WolfyUtils-4.16.9.6

### Server software

Purpur 1.19.3 (1894)

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
I was unable to reproduce it. 
Are there any plugins that you have recently installed, that could conflict with anvils?

**Comment by LcyDev** [comment]
Hmm, I didn't think of that.
I checked the AnvilListener and nothing seems wrong so it maybe a plugin (BanItem or M0-AntiAnvilRename)

**Comment by LcyDev** [comment]
> I was unable to reproduce it. Are there any plugins that you have recently installed, that could conflict with anvils?

This is so weird, i don't remember removing any plugins and now it's not happening anymore.
