### ISSUE TITLE
PacketTooLarge

### ISSUE THREAD

**Issue by ccyounga** [WolfyScript/CustomCrafting#249]
### What happened?

Hello. I've always used the plugin to create custom recipes without using the vanilla recipe book as we have too many items with nbt tags. To my surprise, after updating the plugin to 4.16.6.0, I found that the problem appeared and it was impossible to get rid of it.
I reviewed all the files, I did not find any information about disabling this function, before we had it turned off by default.

### How can the bug be reproduced?

Just make a lot of recipes with nbt tags and enter the game.

### Expected Behaviour?

That it won't send recipes to minecraft by filling up the allowed recipe limit.

### Plugin version

CC 4.16.6.0, WU 4.16.9.6 

### Server software

git-Paper-386 (MC: 1.18.2)

### Relevant log output

```shell
https://imgur.com/cOaCrGB
```

### Submit issue

- [x] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Do you have ProtocolLib installed and up-to-date? 
Not sure from which version you've updated but now each recipe has a 'show in vanilla recipe book' option. 
Could you check a recipe if that option is properly specified?
