### ISSUE TITLE
Problem when used by >1 Players

### ISSUE THREAD

**Issue by xCraimax** [WolfyScript/CustomCrafting#259]
### What happened?

The Item can be duped, when using the cauldron by 2 or more players.
I assume (not tested), that it can be duped more than once - depends on the amount of players.

### How can the bug be reproduced?

- Cook something in the Cauldron
- Then 2 players need to open the result menu
- The first player can take out the result
- The second player can take out the result aswell
- Now you duped the result

### Expected Behaviour?

Not duping and synchronizing between players.

### Plugin version

CustomCrafting 4.16.6.0, WolfyScript 4.16.9.3

### Server software

MC Paper 1.18.2

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Yep, that is indeed a major oversight. I'll have a look at how I can securely handle multiple viewers.
