### ISSUE TITLE
Item Editor - Cannot create non-italic item names

### ISSUE THREAD

**Issue by fireheart3911** [WolfyScript/CustomCrafting#272]
### What happened?

There is currently no way to change item names to not be italic.

### How can the bug be reproduced?

1. Get any item
2. Try to rename it in a way that the name is not italic. Here is the stuff i tried: 
```<#008888>Item Name
</i><#008888>Item Name
<i></i><#008888>Item Name
<reset><#008888>Item Name
/wui <#008888>Item Name
```
3. The item is renamed italic either way

### Expected Behaviour?

You should be able to rename an item to not be italic

### Plugin version

CustomCrafting 4.16.6.4, WolfyUtilities 4.16.10.2

### Server software

Paper 1.19.4

### Relevant log output

```shell
No relevant log
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Adventure provides an option to invert the italic tag. 
https://docs.advntr.dev/minimessage/format.html#decoration

But there is different behaviour between Spigot and Paper here.

On Spigot servers, you need to use a colour tag to make it non-italic.
So e.g. `<#008888>Item Name` will make it non-italic.
However, `<!i>`, etc. do not work on Spigot servers.

On Paper servers, you need to use either `<!i>`, `<!italic>`, `<!em>`, `<i:false>`.
So e.g. `<!i><#008888>Item Name` will make it non-italic.
However, just using the colour tag, like on Spigot servers, won't work.

**Comment by fireheart3911** [comment]
Interesting. I did not see that in the wiki, thanks!
