### ISSUE TITLE
Disabling of cauldrons

### ISSUE THREAD

**Issue by ancap-kun** [WolfyScript/CustomCrafting#280]
### The Problem

Brewery conflicts with the cauldron module. I wanted to disable it, but there is no such option. 

### Solution

Option to disable cauldron module

### Alternatives

I can't imagine some

### Additional Context

Install Brewery and try to make some brew

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
You can change the interaction to the sneaking interaction.
In the config.yml set `workstation.cauldron.interaction` to `SNEAKING`.
To completely block it, set the permission `customcrafting.workstation.cauldron.interact` to false for all players that should not interact with it.
