### ISSUE TITLE
Cauldron Recipes BROKEN

### ISSUE THREAD

**Issue by ConaII** [WolfyScript/CustomCrafting#33]
### What happened?

Cauldron recipes have been broken since some time, I don't remember exactly how long but, yeah, it would be nice to fix it.

### Make a cauldron recipe
`item-input: beacon`
`item-output: slimeball`
`Output-mode: drop`
`item-require-hold: N/A`

`Fire-required: true`
`Water-required: true`
`Water-level: 3`
`Cooking-time: 40`
`Experience: 2.0`
![image](https://user-images.githubusercontent.com/72966048/146624388-f4cce7f4-b263-455d-9002-837e1cd178f5.png)

### After attempting to save
`item-input: reset`
`item-output: saved`
`Output-mode: reset`
`item-require-hold: saved`

`Fire-required: reset`
`Water-required: reset`
`Water-level: saved`
`Cooking-time: saved`
`Experience: saved`
![image](https://user-images.githubusercontent.com/72966048/146624435-31b21cd3-aaf6-420c-8ed0-2e4aaa599d1c.png)

### Expected Behaviour?

Self-explanatory.

### Plugin version

CustomCrafting: 2.16.5.0 WolfyUtilities: 1.8.0.0

### Server software

Paper 1.16.5

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Did some fixes in this commit https://github.com/WolfyScript/CustomCrafting/commit/1592ffbc989541f6b9f5acf439351ea006892fd3
I'm going to leave this issue open till the update is released, and it's confirmed to be fixed.
