### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by explorer3039** [WolfyScript/CustomCrafting#332]
### The Problem

Plugin isn't work on 1.20.2

### Solution

Update it

### Alternatives

1.20.2

### Additional Context

1.20.2

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Yep, I know, the release of 1.20.2 was unfortunate timing right in the middle of my exams phase 😅  I try to have WolfyUtils updated to 1.20.2 very soon. It should be updated by the end of next week. If I can get it setup quickly, maybe this weekend.

**Comment by envizar** [comment]
+1 to "please update it asap"
