### ISSUE TITLE
Not working on latest version (1.20.4)

### ISSUE THREAD

**Issue by golfista** [WolfyScript/CustomCrafting#340]
### What happened?

Not working on latest version

### How can the bug be reproduced?

install paper for mc 1.20.4

### Expected Behaviour?

the plugin to work

### Plugin version

latest

### Server software

paper 1.20.4

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Make sure to update to the latest WolfyUtils version from [Modrinth](https://modrinth.com/plugin/wolfyutils/version/4.16.15-beta.4).
Another version to fix a few minor issues in 1.20.4 like NBTAPI will be released later today.
