### ISSUE TITLE
Disappearing items

### ISSUE THREAD

**Issue by Source4O4** [WolfyScript/CustomCrafting#345]
### What happened?

When I want to add a new recipe, the items in the GUI disappear when placed down. I have tried to use a few versions of both plugins, non worked.

### How can the bug be reproduced?

Make a new recipe, and place down the items in the crafting gui of CC.

### Expected Behaviour?

Items that do not disappear.

### Plugin version

customcrafting-spigot-4.16.8.5.jar, customcrafting-spigot-4.16.8.3.jar, wolfyutils-spigot-4.16.14.1.jar, wolfyutils-spigot-4.16.15-beta.5.jar

### Server software

spigot-1.20.1.jar

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Duplicate #344
