### ISSUE TITLE
Result of recipe is Air if recipe is using MythicMobs items

### ISSUE THREAD

**Issue by Mirayii** [WolfyScript/CustomCrafting#351]
### What happened?

In the recent version of MythicMobs 5.6.0 and up, i'm not able to crafting anything, that contains items from MythicMobs in the recipe. The recipe result is replaced with Air. Tried with several recipes, on several servers, different softwares and doesn't seem like NBT Issue. 
![image](https://github.com/WolfyScript/CustomCrafting/assets/45139953/a04fe590-25bf-47bc-b3ec-e8671092afa3)
![image](https://github.com/WolfyScript/CustomCrafting/assets/45139953/79041d40-2cf1-4c7b-81a4-ef541c7372ad)

### How can the bug be reproduced?

Update to latest development build of MythicMobs 5.6.0 on version 1.20.4 and try to craft items.

### Expected Behaviour?

Result is not returning Air

### Plugin version

CustomCrafting 4.16.9-beta.7, WolfyUtilities 4.16.15-beta.11

### Server software

UniverseSpigot 1.20.4, Purpur 1.20.4

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
I can confirm the same happens on my test server. I'll look into it.

**Comment by WolfyScript** [comment]
That was an easy fix. Will be included in the next beta.
https://github.com/WolfyScript/WolfyUtils-Spigot/commit/705b13603b4463c4b50d1a20ddbac30e97d480c4
