### ISSUE TITLE
CustomCrafting not working 1.20.4

### ISSUE THREAD

**Issue by La-Fougere** [WolfyScript/CustomCrafting#356]
### What happened?

Im in the last version of the plugin and i also downloaded the last version of wolfy utils. Wolfy utils works but CustomCrafting appears in red in the plugin list, so it doesnt work

Help me pls :)

![image_2024-03-03_171436651](https://github.com/WolfyScript/CustomCrafting/assets/64833534/606e2ca8-b1b9-4160-9384-52c1bda9b1e8)

### How can the bug be reproduced?

Just by starting the server...

### Expected Behaviour?

The plugin was supposed to work in 1.20.4

### Plugin version

CustomCrafting v4.16.9 and WolfyUtilities v4.16.15

### Server software

Paper 1.20.4

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by La-Fougere** [comment]
Sorry, it was because of Protocol Lib who doesn work too. I removed it and now CustomCrafting works as well :) 

Sorry for creating useless report.

**Comment by Zhaaaaaaaaa** [comment]
You can get the latest proper version of ProtocolLib if you look for the dev-builds. For some reason the Dev didn't put them up as the main download on the Spigot
