### ISSUE TITLE
Items don't appear in the GUI with existing recipes

### ISSUE THREAD

**Issue by JulekKiwalski** [WolfyScript/CustomCrafting#376]
### What happened?

I know, that no one's going to check this, because the support for this plugin is DEAD. I have a big issue.
So I created a quick recipe and tried to test it out, it worked, but when I tried to access and edit it, I couldn't, because it doesn't simply exist (in the GUI). I also tried restarting the server.

### How can the bug be reproduced?

It happened out of nowhere, tested this out also on an another version of WolfyUtils & CustomCrafting.
1) Create recipe
2) "recipe injected"
3) Open the edit GUI
4) notice, that the folder exists (in my files), but it doesn't exist in my GUI.

### Expected Behaviour?

Fix that, nothing else.

### Plugin version

CustomCrafting 4.16.9.1 & WolfyUtilities 4.17-beta.1

### Server software

Purpur 1.20.1

### Relevant log output

```shell
https://pastebin.com/cNRnvmKZ
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Very sorry for the inconvenience this has caused.

When saving the recipe, it clears the GUI of the Recipe Creator.
So to edit the recipe, you need to open the `/cc` menu and open the Recipe List on the bottom right.
Then when clicking on the chest called 'customcrafting' it should list the directories and recipes you've saved.

In case it does not, please share a screen capture of you creating the recipe and trying to edit it.

**Comment by JulekKiwalski** [comment]
Oh my gosh, I'm so stupid, I've always clicked on the "Item List" category or just bottom left, for some reason, the plugin didn't show my items, this is my fault, I'm very sorry for this incovenience.
