### ISSUE TITLE
Cauldron Random Result doesn't work

### ISSUE THREAD

**Issue by Xiao-MoMi** [WolfyScript/CustomCrafting#51]
### What happened?

It only gives the same result.

### Plugin version

both are 3.16.0.0 

### Server software

purpur 1.17.1

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
I just tested it and it works fine. 
What does your recipe look like? What result items did you set?

**Comment by Xiao-MoMi** [comment]
![image](https://user-images.githubusercontent.com/70987828/150497861-15e601ca-c61e-4572-9869-86b6adb23b10.png)
![image](https://user-images.githubusercontent.com/70987828/150497898-a6ee73ea-e329-4d99-87cf-39affc2dc30c.png)
{
  "group" : "",
  "hidden" : false,
  "priority" : "NORMAL",
  "exactItemMeta" : true,
  "conditions" : {
    "values" : [ ]
  },
  "dropItems" : {
    "enabled" : false,
    "handItem" : null
  },
  "exp" : 0,
  "cookingTime" : 60,
  "waterLevel" : 1,
  "water" : true,
  "fire" : true,
  "result" : {
    "items" : [ {
      "custom_amount" : 1,
      "item" : {
        "==" : "org.bukkit.inventory.ItemStack",
        "v" : 2730,
        "type" : "DEEPSLATE_COAL_ORE"
      }
    }, {
      "custom_amount" : 1,
      "item" : {
        "==" : "org.bukkit.inventory.ItemStack",
        "v" : 2730,
        "type" : "COAL_ORE"
      }
    } ],
    "tags" : [ ],
    "extensions" : [ ]
  },
  "ingredients" : {
    "items" : [ {
      "custom_amount" : 1,
      "item" : {
        "==" : "org.bukkit.inventory.ItemStack",
        "v" : 2730,
        "type" : "BIRCH_PLANKS"
      }
    } ],
    "tags" : [ ],
    "replaceWithRemains" : true,
    "allowEmpty" : false
  }
}

**Comment by Xiao-MoMi** [comment]
https://user-images.githubusercontent.com/70987828/150498702-19227546-d691-4df3-a458-71bad1a1b0c2.mp4

**Comment by WolfyScript** [comment]
Had a closer look into it.  
I realized that this issue occurs right after testing the recipe after saving it.  
When I ran `/cc reload` the randomization worked as intended, and also restarting the server won't break it.
