### ISSUE TITLE
Smithing Table recipes reset back to Use Result Item every reload or restart

### ISSUE THREAD

**Issue by NeuTraLZero** [WolfyScript/CustomCrafting#53]
### What happened?

Every time a server restarts every result items gets changed from Material Only to Use Result Item
No console error.

![2022-01-22_11 51 10](https://user-images.githubusercontent.com/43245485/150625152-8820f6a4-0fea-44eb-8c31-3f6ece29b0c5.png)
![2022-01-22_11 51 14](https://user-images.githubusercontent.com/43245485/150625155-d04eaef1-07a4-4f35-a6d0-e7c074812ed8.png)
![2022-01-22_11 51 18](https://user-images.githubusercontent.com/43245485/150625156-156ffbd6-de6e-4a73-b944-2298d46273b0.png)

Zipped recipe that is used in the screenshots
[toolsandarmorupgrade.zip](https://github.com/WolfyScript/CustomCrafting-Wiki/files/7917657/toolsandarmorupgrade.zip)

### How can the bug be reproduced?

1. Create a smithing table recipe, upgrading iron to diamond sword using a custom item with custom name and NBT for example.
2. Choose Ignore Meta and set it to Material Only
3. Test the recipe without reloading or restarting first, it will work just fine
4. Restart server or reload plugin
5. Test it again, this time the result item will ignore all NBTs of the material item and only give a regular diamond sword

### Expected Behaviour?

The recipe should stay as Material Only

### Plugin version

CustomCrafting 3.16
WolfyUtilities 3.16

### Server software

Purpur 1.18.1

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Thanks for reporting that. Already was aware of it and fixed it in #50. 
The upcoming update will contain that fix.
