### ISSUE TITLE
Changing Recipe Shaped Duplicates JSON File

### ISSUE THREAD

**Issue by BeepoWuff** [WolfyScript/CustomCrafting#57]
### What happened?

Changing the shaped option of an existing recipe will result in the recipe's JSON file being duplicated on save.
e.g. A shaped recipe saved under `crafting_shaped` when changed to shapeless will leave the existing file in `crafting_shaped` but also create a new file in `crafting_shapeless`.
In the above shaped to shapeless example the plugin will also incorrectly load the shaped recipe on server restarts.

### How can the bug be reproduced?

1. Create and save a shaped crafting recipe
2. Change the recipe to shapeless and save again

### Expected Behaviour?

When changing a recipe's shape the old JSON file should be removed upon save

### Plugin version

CustomCrafting 3.16.0.0, WolfyUtilities 3.16.0.0

### Server software

Paper 1.18.1

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
3.16.1 should fix this, but the free version indeed still has this issue.
See https://github.com/WolfyScript/CustomCrafting/pull/52

**Comment by BeepoWuff** [comment]
I tested this on my dev build and there appears to be a slight issue when changing shapes.
After changing the shape of a recipe it is completely removed from the loaded recipes. Not showing in the Recipe List and not being craftable until running a `/cc reload`.

**Comment by WolfyScript** [comment]
This should be fixed since somewhere around v3.16.2. Recipe types are specified into the JSON file itself now.
