### ISSUE TITLE
Scoreboard Score Crafting Condition

### ISSUE THREAD

**Issue by PhuryWasTaken** [WolfyScript/CustomCrafting#64]
### The Problem

No not really, just inconvenience.

### Solution

A crafting condition which checks if a player has a certain amount of score in a scoreboard objective. 

It might look something like this:
has score?
objective: Skeleton Kills
score: 15

I would also recommend allowing some form of comparators that can be used in the score (if possible). Example:

has score?
objective: Skeleton Kills
score >15

### Alternatives

None.

### Additional Context

None.

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
That is indeed a good idea for a condition, and I'll see how I can implement it.

I really like the idea with the comparators. I won't just add comparators, though, as this gives us the opportunity to create an overall better system.
That means I will extend on that idea and say we add expressions like `if`, `or`, `and`. And perhaps value providers, that can provide values based on input too (e.g. placeholders).
All part of WolfyUtilities for usage in other plugins too.
