### ISSUE TITLE
Create please group recipes in vanilla book!

### ISSUE THREAD

**Issue by MrJorman** [WolfyScript/CustomCrafting#91]
### The Problem

Create please group recipes in vanilla book!

### Solution

Example groups recipes in Vanilla Book.

![image](https://user-images.githubusercontent.com/55187962/157796731-5ee35882-16c3-4ea2-978d-53cf138e87f2.png)

### Alternatives

Example groups recipes in Vanilla Book.

![image](https://user-images.githubusercontent.com/55187962/157796731-5ee35882-16c3-4ea2-978d-53cf138e87f2.png)

### Additional Context

Example groups recipes in Vanilla Book.

![image](https://user-images.githubusercontent.com/55187962/157796731-5ee35882-16c3-4ea2-978d-53cf138e87f2.png)

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
This is already possible.
In the recipe creator (bottom right) you can set a group.
Recipes with the same group are then grouped together in the vanilla and custum recipe book.

**Comment by MrJorman** [comment]
@WolfyScript no working.

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/158037254-a06bd7f3-5bad-491f-8b62-b09e382528e1.png)
recipes group: spawner
![image](https://user-images.githubusercontent.com/55187962/158037260-3a803b35-0a36-48bd-a2f4-844c77c337c1.png)
recipes group: spawner

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/158037267-7c0760ed-6979-40d8-8c5c-2f1b3ab4c70b.png)
who group?)

**Comment by MrJorman** [comment]
i restarted server moore time, and no working your function groups.

**Comment by MrJorman** [comment]
okay, i found bug. if the recipe has already been added, then you need to re-create it with the group, the group will not work in the already added recipe. @WolfyScript

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/158037365-512b995f-3d2e-4436-9894-baa83cf6946b.png)
okay fixed.
